// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdb7hamtcAFRWtbOA5sqBY__jzbsUHEW8',
    appId: '1:962188079667:web:c00263a75b44e0dd302946',
    messagingSenderId: '962188079667',
    projectId: 'todolist-ccf71',
    authDomain: 'todolist-ccf71.firebaseapp.com',
    storageBucket: 'todolist-ccf71.appspot.com',
    measurementId: 'G-EX11BX9YBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOEGw-W4xrSHMkad-UM9sNBRUs_7OfmrE',
    appId: '1:962188079667:android:b93ec8a5a30c732a302946',
    messagingSenderId: '962188079667',
    projectId: 'todolist-ccf71',
    storageBucket: 'todolist-ccf71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXsmZcmuRTdqnH4yP3Y639vLddHN88rdc',
    appId: '1:962188079667:ios:3dc9aa7cae33f545302946',
    messagingSenderId: '962188079667',
    projectId: 'todolist-ccf71',
    storageBucket: 'todolist-ccf71.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXsmZcmuRTdqnH4yP3Y639vLddHN88rdc',
    appId: '1:962188079667:ios:3dc9aa7cae33f545302946',
    messagingSenderId: '962188079667',
    projectId: 'todolist-ccf71',
    storageBucket: 'todolist-ccf71.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdb7hamtcAFRWtbOA5sqBY__jzbsUHEW8',
    appId: '1:962188079667:web:0b3152efa1722c5a302946',
    messagingSenderId: '962188079667',
    projectId: 'todolist-ccf71',
    authDomain: 'todolist-ccf71.firebaseapp.com',
    storageBucket: 'todolist-ccf71.appspot.com',
    measurementId: 'G-D5T07JC67W',
  );
}
